const products = [
  {
    id: 1,
    name: "Airpods Wireless Bluetooth Headphones",
    image: "/images/airpods.png",
    description:
      "Bluetooth technology lets you connect it with compatible devices wirelessly High-quality AAC audio offers immersive listening experience Built-in microphone allows you to take calls while working",
    brand: "Apple",
    category: "Electronics",
    price: 179.99,
    countInStock: 11,
    rating: 4.5,
    numReviews: 12,
    featured: true,
  },
  {
    id: 2,
    name: "Beats Pill+ Portable Speaker",
    image: "/images/boxa.png",
    description:
      "Beats Pill+ is designed to fill the room with a rich, clear sound field that has as much power as it does definition",
    brand: "Beats",
    category: "Electronics",
    price: 119.99,
    countInStock: 9,
    rating: 4.0,
    numReviews: 8,
  },
  {
    id: 3,
    name: "GoPro",
    image: "/images/gopro.png",
    description:
      "Small camera the takes the best qualities of point-and-shoots and camcorders and packs them into a rugged frame that's smaller, waterproof, and virtually indestructible.",
    brand: "GoPro",
    category: "Electronics",
    price: 399.99,
    countInStock: 5,
    rating: 3,
    numReviews: 12,
  },
  {
    id: 4,
    name: "Iphone 12",
    image: "/images/iphone.png",
    description:
      "The iPhone 12 and iPhone 12 mini are Apple's mainstream flagship iPhones for 2020. The phones come in 6.1-inch and 5.4-inch sizes with identical features, including support for faster 5G cellular networks, OLED displays, improved cameras, and Apple's latest A14 chip, all in a completely refreshed design",
    brand: "Apple",
    category: "Electronics",
    price: 899.99,
    countInStock: 20,
    rating: 5,
    numReviews: 14,
    featured: true,
  },
  {
    id: 5,
    name: "Dell Laptop",
    image: "/images/laptop.png",
    description:
      "It is powered by a Core i5 processor and it comes with 8GB of RAM. The Dell Inspiron 15 packs 1TB of HDD storage. Graphics are powered by AMD Radeon 530 Graphics.",
    brand: "Dell",
    category: "Electronics",
    price: 599.99,
    countInStock: 3,
    rating: 3.8,
    numReviews: 4,
  },
  {
    id: 6,
    name: "Playstation 5",
    image: "/images/playstation.png",
    description:
      "The PlayStation 5's main hardware features include a solid-state drive customized for high-speed data streaming to enable significant improvements in storage performance, an AMD GPU capable of 4K resolution display at up to 120 frames per second",
    brand: "Amazon",
    category: "Electronics",
    price: 499.99,
    countInStock: 0,
    rating: 4.4,
    numReviews: 2,
  },
  {
    id: 7,
    name: "iPad",
    image: "/images/ipad.png",
    description:
      "It’s a magical piece of glass ,you can use it with touch, pencil, keyboard, and now trackpad.",
    brand: "Apple",
    category: "Electronics",
    price: 699.99,
    countInStock: 2,
    rating: 5,
    numReviews: 5,
  },
  {
    id: 8,
    name: "Logitech G Pro Wireless",
    image: "/images/gpro.png",
    description:
      "The Logitech G Pro Wireless is one of the best overall packages you can get in a gaming mouse. With a real ambidextrous experience, this mouse brings an efficient hero sensor up to 16,000 dpi, the incredibly fast lightspeed wireless 1 ms response rate, and an ultra-lightweight design at just 80 grams.",
    brand: "Logitech",
    category: "Electronics",
    price: 120.0,
    countInStock: 22,
    rating: 4.8,
    numReviews: 45,
    featured: true,
  },
  {
    id: 9,
    name: "Razer Huntsman Gaming Keyboard",
    image: "/images/razer.png",
    description:
      "The Razer Huntsman introduces the new Razer Opto-Mechanical Switch, utilizing optical technology for unmatched speed, and a key stabilizer bar so every keypress is precise and accurate.",
    brand: "Razer",
    category: "Electronics",
    price: 149.99,
    countInStock: 9,
    rating: 4.0,
    numReviews: 10,
  },
];

export default products;
